# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPlacementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(blank=True, max_length=255, null=True)),
                ('job_offers', models.JSONField(blank=True, null=True)),
                ('education_location', models.TextField(blank=True, null=True)),
                ('education_location_other', models.TextField(blank=True, null=True)),
                ('education_degree', models.TextField(blank=True, null=True)),
                ('competitive_exam', models.TextField(blank=True, null=True)),
                ('competitive_exam_other', models.TextField(blank=True, null=True)),
                ('business_sector', models.TextField(blank=True, null=True)),
                ('job_domain', models.TextField(blank=True, null=True)),
                ('job_domain_other', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
