# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('enrollment_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FSEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('enrollment_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FSEnrollmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('progress_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('assessment_status', models.BooleanField(blank=True, default=False, null=True)),
                ('course_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('certificate_issued', models.BooleanField(blank=True, default=False, null=True)),
                ('certificate_issued_at', models.DateField(blank=True, null=True)),
                ('fs_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fs.fscourse')),
            ],
        ),
    ]
