# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kp', '0001_initial'),
        ('college', '0001_initial'),
        ('fs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsenrollmentprogress',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kp.knowledgepartner'),
        ),
        migrations.AddField(
            model_name='fsenrollment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.college'),
        ),
        migrations.AddField(
            model_name='fsenrollment',
            name='fs_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fs.fscourse'),
        ),
        migrations.AddField(
            model_name='fsenrollment',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kp.knowledgepartner'),
        ),
    ]
