# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_release', models.BooleanField(default=False)),
                ('invitation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(default=0)),
                ('college_name', models.CharField(blank=True, max_length=300, null=True)),
                ('college_code', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mailed', models.BooleanField(default=False)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('spoc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college_type', models.IntegerField(blank=True, null=True)),
                ('management_type', models.IntegerField(blank=True, null=True)),
                ('year_of_establishment', models.IntegerField(blank=True, null=True)),
                ('total_faculty_count', models.IntegerField(default=0)),
                ('total_1st_year_students_count', models.IntegerField(default=0)),
                ('total_2nd_year_students_count', models.IntegerField(default=0)),
                ('total_3rd_year_students_count', models.IntegerField(default=0)),
                ('total_4th_year_students_count', models.IntegerField(default=0)),
                ('total_students_count', models.IntegerField(default=0)),
                ('details_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('town_city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('subscription_status', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('taluk', models.CharField(blank=True, max_length=255, null=True)),
                ('is_students_verified', models.BooleanField(default=False)),
                ('course_allocation', models.IntegerField(default=0)),
                ('external_assessment', models.IntegerField(default=0)),
                ('principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_email', models.CharField(blank=True, max_length=255, null=True)),
                ('placement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('placement_mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('placement_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '02 - College',
            },
        ),
        migrations.CreateModel(
            name='CollegeFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('assigned_faculty_id', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_educational_qualification', models.TextField(blank=True, null=True)),
                ('pg_specialization', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.TextField(blank=True, null=True)),
                ('in_industry_research_others', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('has_master_trainer_on_honoraraium_basis', models.IntegerField(default=0)),
                ('any_relevant_certification', models.TextField(blank=True, null=True)),
                ('details_of_skills', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeOtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.IntegerField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_otp_send', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College Otp Verification',
            },
        ),
        migrations.CreateModel(
            name='CollegeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_order_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_fee', models.FloatField(default=0)),
                ('payment_mode', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_done_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '03 - College Subscription',
            },
        ),
        migrations.CreateModel(
            name='FacultyFDPDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('technology', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationStepOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('csv_file', models.FileField(upload_to='college_registrations')),
                ('total_count', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('already_exist_count', models.IntegerField(default=0)),
                ('is_mailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '01 - Registration',
            },
        ),
    ]
