# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datarepo', '0001_initial'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_colleges', models.BigIntegerField(default=0)),
                ('total_no_of_colleges_invited', models.BigIntegerField(default=0)),
                ('total_no_of_colleges_registered', models.BigIntegerField(default=0)),
                ('total_no_of_colleges_subscribed', models.BigIntegerField(default=0)),
                ('college_type_1', models.BigIntegerField(default=0)),
                ('college_type_2', models.BigIntegerField(default=0)),
                ('college_type_3', models.BigIntegerField(default=0)),
                ('college_type_4', models.BigIntegerField(default=0)),
                ('college_type_5', models.BigIntegerField(default=0)),
                ('total_no_of_students', models.BigIntegerField(default=0)),
                ('college_type_1_students', models.BigIntegerField(default=0)),
                ('college_type_2_students', models.BigIntegerField(default=0)),
                ('college_type_3_students', models.BigIntegerField(default=0)),
                ('college_type_4_students', models.BigIntegerField(default=0)),
                ('college_type_5_students', models.BigIntegerField(default=0)),
                ('total_no_of_male_students', models.BigIntegerField(default=0)),
                ('total_no_of_female_students', models.BigIntegerField(default=0)),
                ('total_no_of_other_students', models.BigIntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_type', models.IntegerField(blank=True, null=True)),
                ('total_no_of_students', models.BigIntegerField(default=0)),
                ('total_no_of_students_invited', models.BigIntegerField(default=0)),
                ('total_no_of_students_registered', models.BigIntegerField(default=0)),
                ('total_no_of_students_subscribed', models.BigIntegerField(default=0)),
                ('total_no_of_male_students', models.BigIntegerField(default=0)),
                ('total_no_of_female_students', models.BigIntegerField(default=0)),
                ('total_no_of_other_students', models.BigIntegerField(default=0)),
                ('affiliated_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.affiliateduniversity')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.college')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.district')),
            ],
        ),
    ]
