# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion
import skillofferings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='coursera')),
                ('status', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quality_of_course', models.CharField(blank=True, max_length=255, null=True)),
                ('quality_of_trainer', models.CharField(blank=True, max_length=255, null=True)),
                ('has_the_course_increased_your_motivation_to_upskill', models.CharField(blank=True, max_length=255, null=True)),
                ('did_you_have_supportive_teachers_who_could_help_with_queries', models.CharField(blank=True, max_length=255, null=True)),
                ('time_allocated_to_you_for_the_training_and_homework_sufficient', models.CharField(blank=True, max_length=255, null=True)),
                ('doubt_clearing_sessions_held_by_the_trainer', models.CharField(blank=True, max_length=255, null=True)),
                ('doubts_get_cleared', models.CharField(blank=True, max_length=255, null=True)),
                ('is_hybrid_training_more_effective', models.CharField(blank=True, max_length=255, null=True)),
                ('training_sufficient_with_days', models.CharField(blank=True, max_length=255, null=True)),
                ('interested_in_working_in_large_projects', models.CharField(blank=True, max_length=255, null=True)),
                ('repeat_the_training', models.CharField(blank=True, max_length=255, null=True)),
                ('enjoyment_in_course', models.TextField(blank=True, null=True)),
                ('course_like_to_take', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MandatoryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.IntegerField(default=0)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKillOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_delivery', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('outcomes', models.TextField(blank=True, null=True)),
                ('course_content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.IntegerField(default=0)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('offering_type', models.IntegerField(blank=True, null=True)),
                ('offering_kind', models.IntegerField(blank=True, null=True)),
                ('job_category', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('ea_count', models.IntegerField(default=0)),
                ('ia_count', models.IntegerField(blank=True, null=True)),
                ('manually_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SKillOfferingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('offering_type', models.IntegerField(blank=True, null=True)),
                ('offering_kind', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SKillOfferingEnrollmentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, default=skillofferings.models.get_uuid, max_length=40, null=True, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='skill_offering/certificates')),
                ('certificate_no', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('college_type', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKillOfferingEnrollmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ea_1', models.CharField(blank=True, max_length=255, null=True)),
                ('ea_2', models.CharField(blank=True, max_length=255, null=True)),
                ('ea_3', models.CharField(blank=True, max_length=255, null=True)),
                ('ia_1', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_2', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_3', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_4', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_5', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_marks', models.CharField(blank=True, max_length=100, null=True)),
                ('external_marks', models.CharField(blank=True, max_length=100, null=True)),
                ('progress_percentage', models.FloatField(default=0)),
                ('assessment_status', models.BooleanField(default=False)),
                ('assessment_data', models.JSONField(blank=True, null=True)),
                ('course_complete', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_issued_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TempA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('skill_offering_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skillofferingenrollment')),
            ],
        ),
    ]
