# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datarepo', '0001_initial'),
        ('skillofferings', '0001_initial'),
        ('kp', '0002_initial'),
        ('college', '0001_initial'),
        ('lms', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempa',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='subtechnology',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillofferings.technology'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollmentprogress',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kp.knowledgepartner'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollmentprogress',
            name='skill_offering_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skillofferingenrollment'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollmentcertificate',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kp.knowledgepartner'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollmentcertificate',
            name='skill_offering_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skillofferingenrollment'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.college'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollment',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.collegefaculty'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollment',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kp.knowledgepartner'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollment',
            name='lms_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollment',
            name='skill_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skilloffering'),
        ),
        migrations.AddField(
            model_name='skillofferingenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='branch',
            field=models.ManyToManyField(blank=True, null=True, to='datarepo.branch'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='knowledge_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kp.knowledgepartner'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='lms_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='skillofferings.specialisation'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='sub_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.subtechnology'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.technology'),
        ),
        migrations.AddField(
            model_name='skilloffering',
            name='year_of_study',
            field=models.ManyToManyField(blank=True, null=True, to='datarepo.yearofstudy'),
        ),
        migrations.AddField(
            model_name='mandatorycourse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datarepo.branch'),
        ),
        migrations.AddField(
            model_name='mandatorycourse',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.college'),
        ),
        migrations.AddField(
            model_name='mandatorycourse',
            name='skill_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skilloffering'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skillofferingenrollment'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='skill_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skilloffering'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
        migrations.AddField(
            model_name='coursebulkupload',
            name='skill_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skillofferings.skilloffering'),
        ),
    ]
