# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unique_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_content', models.JSONField(blank=True, null=True)),
                ('course_objective', models.JSONField(blank=True, null=True)),
                ('course_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('number_of_videos', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('main_stream', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_stream', models.CharField(blank=True, max_length=255, null=True)),
                ('system_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('has_subtitles', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client_status', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.IntegerField(default=0)),
                ('course_unique_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_content', models.JSONField(blank=True, null=True)),
                ('course_objective', models.JSONField(blank=True, null=True)),
                ('course_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.FloatField(blank=True, default=0, null=True)),
                ('number_of_videos', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('main_stream', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_stream', models.CharField(blank=True, max_length=255, null=True)),
                ('system_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('has_subtitles', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client_status', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LmsApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('sub_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LMSClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('client_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('lms_dev_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('client_logo', models.ImageField(blank=True, null=True, upload_to='lms_clients')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0)),
                ('assessment_status', models.BooleanField(default=False)),
                ('course_complete', models.BooleanField(default=False)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_issued_at', models.DateField(blank=True, null=True)),
                ('subscription_reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_on', models.DateTimeField(blank=True, null=True)),
                ('is_mandatory', models.IntegerField(blank=True, null=True)),
                ('temp_z', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assessment_data', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.course')),
                ('lms_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lmsclient')),
            ],
        ),
    ]
