# Generated by Django 4.0.5 on 2023-07-05 12:03

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTemporaryFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('college_type', models.IntegerField(blank=True, null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mailed', models.BooleanField(default=False)),
                ('invitation_id', models.CharField(blank=True, default=student.models.student_invitation_id_gen, max_length=40, null=True, unique=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('registration_status', models.IntegerField(default=0)),
                ('verification_status', models.IntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('is_temporary_roll_number', models.BooleanField(default=False)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('caste', models.IntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='student/caste_certificate/')),
                ('is_pass_out', models.BooleanField(default=False)),
                ('provisional_certificate', models.FileField(blank=True, null=True, upload_to='student/provisional_certificate/')),
                ('concessions', models.IntegerField(blank=True, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, default=2, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('current_village', models.CharField(blank=True, max_length=255, null=True)),
                ('current_town_city', models.CharField(blank=True, max_length=255, null=True)),
                ('current_district', models.CharField(blank=True, max_length=255, null=True)),
                ('current_state', models.CharField(blank=True, max_length=255, null=True)),
                ('current_pincode', models.IntegerField(blank=True, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_village', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_town_city', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_pincode', models.IntegerField(blank=True, null=True)),
                ('hall_ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('year_of_graduation', models.IntegerField(blank=True, null=True)),
                ('tenth_pass_out_year', models.IntegerField(blank=True, null=True)),
                ('tenth_cgpa', models.FloatField(blank=True, null=True)),
                ('intermediate_pass_out_year', models.IntegerField(blank=True, null=True)),
                ('is_first_year_in_degree', models.BooleanField(blank=True, null=True)),
                ('current_graduation_cgpa', models.FloatField(blank=True, null=True)),
                ('has_backlogs', models.BooleanField(blank=True, null=True)),
                ('subscription_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_free_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '01 - Student',
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_order_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_fee', models.FloatField(default=0)),
                ('payment_mode', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_done_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '03 - Student Subscription',
            },
        ),
        migrations.CreateModel(
            name='TemporaryFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('college_type', models.IntegerField(blank=True, null=True)),
                ('csv_file_data', models.JSONField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistrationStepOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('csv_file', models.FileField(upload_to='college_registrations')),
                ('total_count', models.IntegerField(default=0)),
                ('valid_count', models.IntegerField(default=0)),
                ('invalid_count', models.IntegerField(default=0)),
                ('already_exist_count', models.IntegerField(default=0)),
                ('is_mailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.college')),
            ],
            options={
                'verbose_name': '01 - Registration',
            },
        ),
    ]
